name: Deploy Application

on:
  workflow_run:
    workflows: ["Build Project"]
    types:
      - completed

permissions:
  contents: read
  actions: write

jobs:
  versioning:
    name: Versioning Project
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      docker-container-registry: ${{ steps.docker-image-registry.outputs.docker-container-registry }}
    
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: version
          path: ./
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Get version from file
        id: get-version
        run: |
          VALUE=$(cat ./version.txt)
          echo "::notice:: $VALUE"
          echo "version=$VALUE" >> "$GITHUB_OUTPUT"
      
      - name: Generate docker image registry
        id: docker-image-registry
        run: |
          echo "docker-container-registry=${{ vars.DOCKER_CONTAINER_REGISTRY }}/${{ vars.DOCKERHUB_REPOSITORY }}:${{ steps.get-version.outputs.version }}" >> "$GITHUB_OUTPUT"

  deploy-to-google-cloud:
    name: Deploy to Google Cloud
    needs: versioning
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        environment: [staging, production]
    environment: ${{ matrix.environment }}

    steps:
      - uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - uses: google-github-actions/deploy-cloudrun@v3
        id: deploy-to-cloud-run
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          service: ${{ vars.GCP_RUN_SERVICE }}
          image: ${{ needs.versioning.outputs.docker-container-registry }}
          region: ${{ vars.GCP_RUN_REGION }}
      
      - name: 'Test the deployment'
        run: |-
          echo "::notice:: ${{ steps.deploy-to-cloud-run.outputs.url }}/index.html"
          curl -I --fail "${{ steps.deploy-to-cloud-run.outputs.url }}/index.html"

  deploy-to-microsoft-azure:
    name: Deploy to Microsoft Azure
    needs: versioning
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        environment: [staging, production]
    environment: ${{ matrix.environment }}

    steps:
      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          resource-group-name: ${{ vars.AZURE_RESOURCE_GROUP }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ needs.versioning.outputs.docker-container-registry }}

      - name: 'Test the deployment'
        run: |-
          echo "::notice:: ${{ steps.deploy-to-webapp.outputs.url }}/index.html"
          curl -I --fail "${{ steps.deploy-to-webapp.outputs.url }}/index.html"

  deploy-to-aws:
    name: Deploy to Amazon Web Services
    needs: versioning
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        environment: [staging, production]
    environment: ${{ matrix.environment }}
    env:
      TASK_DEDINITION_PATH: ./infra/aws/amazon-ecs-task-definition.json

    steps:
      - uses: actions/checkout@v7

      - name: Configura AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      # - name: Deploy to AWS ECS
      #   id: deploy-to-ecs
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      #   with:
      #     cluster: ${{ vars.AWS_ECS_CLUSTER_NAME }}
      #     service: ${{ vars.AWS_ECS_SERVICE_NAME }}
      #     task-definition: ${{ vars.AWS_ECS_TASK_DEFINITION }}
      #     container-image: ${{ needs.versioning.outputs.docker-container-registry }}
      #     container-name: ${{ vars.AWS_ECS_CONTAINER_NAME }}
      #     access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # - name: 'Test the deployment'
        run: |-
          echo "::notice:: ${{ steps.deploy-to-ecs.outputs.url }}/index.html"
          curl -I --fail "${{ steps.deploy-to-ecs.outputs.url }}/index.html"